name: Node.js Build Test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 2

    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Build
      run: |
        yarn install
        yarn build
